name: z_m3u_handler
description: Flutter package used to to handle m3u data with firestore(for favorites and history) and local databases.
version: 0.0.7

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.3.1
  dio: ^4.0.6
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  path: ^1.8.2
  path_provider: ^2.0.12
  shared_preferences: ^2.0.17
  shared_preferences_android: ^2.0.15
  shared_preferences_ios: ^2.1.1
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
